
# This is a complete configuration to deploy Loki backed by a s3-compatible API
# like MinIO for storage.
# Index files will be written locally at /loki/index and, eventually, will be shipped to the storage via tsdb-shipper.

auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true

schema_config:
  configs:
  - from: 2020-05-15
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: index_
      period: 24h

ruler:
  storage:
    s3:
      bucketnames: loki-ruler
# storage_config:
  # boltdb_shipper:
  #   active_index_directory: /loki/index
  #   cache_location: /loki/index_cache
  #   resync_interval: 5s
  #   shared_store: s3
  # aws:
  #   s3: http://minioadmin:minioadmin@minio.:9000/loki
  #   s3forcepathstyle: true